name: Fishingcrates
version: '${project.version}'
main: pixelpacker.fishingcrates.FishingCrates
api-version: 1.19
commands:
  givecrate:
    description: Allows for an admin to give a player a crate.
    permission: fishingcrates.admin
    usage: /givecrate <player> <BasicCrate | NotBasicCrate> [Number of Crates]
    aliases: gcrate
    permission-message: You do not have the permissions to give a player a crate.